/* eslint-disable camelcase */

exports.shorthands = undefined

exports.up = pgm => {
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Īsknābja zoss', 'Pink-footed Goose', 'Anser brachyrhynchus', 'Короткоклювый гуменник', id FROM birds_class WHERE name_en = 'Anser'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazā zoss', 'Lesser White-fronted Goose', 'Anser erythropus', 'Пискулька', id FROM birds_class WHERE name_en = 'Anser'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Kalnu zoss', 'Bar-headed Goose', 'Anser indicus', 'Горный гусь', id FROM birds_class WHERE name_en = 'Anser'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sniega zoss', 'Snow Goose', 'Chen caerulescens', 'Белый гусь', id FROM birds_class WHERE name_en = 'Anser'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melngalvas zoss', 'Dark-bellied Brant Goose', 'Branta bernicla', 'Чёрная казарка', id FROM birds_class WHERE name_en = 'Branta'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Bafina zoss', 'Cackling Goose', 'Branta hutchinsii', 'Малая канадская казарка', id FROM birds_class WHERE name_en = 'Branta'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sarkankakla zoss', 'Red-breasted Goose', 'Branta ruficollis', 'Краснозобая казарка', id FROM birds_class WHERE name_en = 'Branta'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ēģiptes zoss', 'Egyptian Goose', 'Alopochen eagyptiaca', 'Нильский гусь', id FROM birds_class WHERE name_en = 'Alopochen'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnais gulbis', 'Black Swan', 'Cygnus atratus', 'Чёрный лебедь', id FROM birds_class WHERE name_en = 'Cygnus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Rudā dižpīle', 'Ruddy Shelduck', 'Tadorna ferruginea', 'Огарь', id FROM birds_class WHERE name_en = 'Tadorna'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Koku pīle', 'Wood Duck', 'Aix sponsa', 'Каролинская утка', id FROM birds_class WHERE name_en = 'Aix'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mandarīnpīle', 'Mandarin Duck', 'Aix galericulata', 'Мандаринка', id FROM birds_class WHERE name_en = 'Aix'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltvaigu garkaklis', 'White-cheeked Pintail', 'Anas bahamensis', 'Белощёкая шилохвость', id FROM birds_class WHERE name_en = 'Anas'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lielgalvis', 'Red-crested Pochard', 'Netta rufina', 'Красноносый нырок', id FROM birds_class WHERE name_en = 'Netta'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltacis', 'Ferruginous Duck', 'Aythya nyroca', 'Белоглазый нырок', id FROM birds_class WHERE name_en = 'Aythya'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ķerra', 'Greater Scaup', 'Aythya marila', 'Морская чернеть', id FROM birds_class WHERE name_en = 'Aythya'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Stellera pūkpīle', 'Steller''s Eider', 'Polysticta stelleri', 'Сибирская гага', id FROM birds_class WHERE name_en = 'Polysticta'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Krāšņā pūkpīle', 'King Eider', 'Somateria spectabilis', 'Гага-гребенушка', id FROM birds_class WHERE name_en = 'Somateria'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Parastā pūkpīle', 'Common Eider', 'Somateria mollissima', 'Обыкновенная гага', id FROM birds_class WHERE name_en = 'Somateria'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Arlekīnpīle', 'Harlequin Duck', 'Histrionicus histrionicus', 'Каменушка', id FROM birds_class WHERE name_en = 'Histrionicus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Stejnegera pīle', 'Stejneger''s Scoter', 'Melanitta stejnegeri', 'Горбоносый турпан', id FROM birds_class WHERE name_en = 'Melanitta'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Garknābja gaura', 'Red-breasted Merganser', 'Mergus serrator', 'Средний крохаль', id FROM birds_class WHERE name_en = 'Mergus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltgalvas zilknābis', 'White-headed Duck', 'Oxyura leucocephala', 'Савка', id FROM birds_class WHERE name_en = 'Oxyura'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Laukirbe', 'Grey Partridge', 'Perdix perdix', 'Серая куропатка', id FROM birds_class WHERE name_en = 'Perdix'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Paipala', 'Common Quail', 'Coturnix coturnix', 'Обыкновенный перепел', id FROM birds_class WHERE name_en = 'Coturnix'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Parastais fazāns', 'Common Pheasant', 'Phasianus colchicus', 'Обыкновенный фазан', id FROM birds_class WHERE name_en = 'Phasianus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mednis', 'Western Capercaillie', 'Tetrao urogallus', 'Глухарь', id FROM birds_class WHERE name_en = 'Tetrao'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mežirbe', 'Hazel Grouse', 'Bonasa bonasia', 'Рябчик', id FROM birds_class WHERE name_en = 'Tetrastes'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltirbe', 'Willow Ptarmigan', 'Lagopus lagopus', 'Белая куропатка', id FROM birds_class WHERE name_en = 'Lagopus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Brūnkakla gārgale', 'Red-throated Loon', 'Gavia stellata', 'Краснозобая гагара', id FROM birds_class WHERE name_en = 'Gavia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnkakla gārgale', 'Black-throated Loon', 'Gavia arctica', 'Чернозобая гагара', id FROM birds_class WHERE name_en = 'Gavia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Polārā gārgale', 'Great Northern Loon', 'Gavia immer', 'Черноклювая гагара', id FROM birds_class WHERE name_en = 'Gavia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dzeltenknābja gārgale', 'Yellow-billed Loon', 'Gavia adamsii', 'Белоклювая гагара', id FROM birds_class WHERE name_en = 'Gavia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais dūkuris', 'Little Grebe', 'Tachybaptus ruficollis', 'Малая поганка', id FROM birds_class WHERE name_en = 'Tachybaptus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ragainais dūkuris', 'Horned Grebe', 'Podiceps auritus', 'Красношейная поганка', id FROM birds_class WHERE name_en = 'Podiceps'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnkakla dūkuris', 'Black-necked Grebe', 'Podiceps nigricollis', 'Черношейная поганка', id FROM birds_class WHERE name_en = 'Podiceps'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sārtais flamings', 'Greater Flamingo', 'Phoenicopterus roseus', 'Розовый фламинго', id FROM birds_class WHERE name_en = 'Phoenicopterus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tumšais vētrasputns', 'Sooty Shearwater', 'Puffinus griseus', 'Серый буревестник', id FROM birds_class WHERE name_en = 'Ardenna'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ziemeļu vētrasburātājs', 'Leach''s Storm Petrel', 'Oceanodroma leucorhoa', 'Северная качурка', id FROM birds_class WHERE name_en = 'Hydrobates'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnais stārķis', 'Black Stork', 'Ciconia nigra', 'Чёрный аист', id FROM birds_class WHERE name_en = 'Ciconia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ziemeļu sulla', 'Northern Gannet', 'Morus bassanus', 'Северная олуша', id FROM birds_class WHERE name_en = 'Morus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais jūraskrauklis', 'Pygmy Cormorant', 'Phalacrocorax pygmeus', 'Малый баклан', id FROM birds_class WHERE name_en = 'Microcarbo'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sārtais pelikāns', 'Great White Pelican', 'Pelecanus onocrotalus', 'Розовый пеликан', id FROM birds_class WHERE name_en = 'Pelecanus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Cirtainais pelikāns', 'Dalmatian Pelican', 'Pelecanus crispus', 'Кудрявый пеликан', id FROM birds_class WHERE name_en = 'Pelecanus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais dumpis', 'Little Bittern', 'Ixobrychus minutus', 'Малая выпь', id FROM birds_class WHERE name_en = 'Ixobrychus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais baltais gārnis', 'Little Egret', 'Egretta garzetta', 'Малая белая цапля', id FROM birds_class WHERE name_en = 'Egretta'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Brūnais ibiss', 'Glossy Ibis', 'Plegadis falcinellus', 'Каравайка', id FROM birds_class WHERE name_en = 'Plegadis'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnplecu klija', 'Black-shouldered Kite', 'Elanus caeruleus', 'Чернокрылый дымчатый коршун', id FROM birds_class WHERE name_en = 'Elanus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Raibais grifs', 'Rueppell''s Griffon', 'Gyps rueppellii', 'Африканский сип', id FROM birds_class WHERE name_en = 'Gyps'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltgalvas grifs', 'Griffon Vulture', 'Gyps fulvus', 'Белоголовый сип', id FROM birds_class WHERE name_en = 'Gyps'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnais grifs', 'Cinereous Vulture', 'Aegypius monachus', 'Чёрный гриф', id FROM birds_class WHERE name_en = 'Aegypius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Čūskērglis', 'Short-toed Snake Eagle', 'Circaetus gallicus', 'Змееяд', id FROM birds_class WHERE name_en = 'Circaetus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Stepes lija', 'Pallid Harrier', 'Circus macrourus', 'Степной лунь', id FROM birds_class WHERE name_en = 'Circus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Pļavu lija', 'Montagu''s Harrier', 'Circus pygargus', 'Луговой лунь', id FROM birds_class WHERE name_en = 'Circus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Vidējais ērglis', 'Greater Spotted Eagle', 'Aquila clanga', 'Большой подорлик', id FROM birds_class WHERE name_en = 'Clanga'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Stepes ērglis', 'Steppe Eagle', 'Aquila nipalensis', 'Степной орёл', id FROM birds_class WHERE name_en = 'Aquila'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Karaliskais ērglis', 'Imperial Eagle', 'Aquila heliaca', 'Могильник', id FROM birds_class WHERE name_en = 'Aquila'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Pundurērglis', 'Booted Eagle', 'Aquila pennata', 'Орёл-карлик', id FROM birds_class WHERE name_en = 'Hieraaetus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dienvidu karakara', 'Southern Caracara', 'Caracara plancus', 'Обыкновенная каракара', id FROM birds_class WHERE name_en = 'Caracara'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Rudgalvas piekūns', 'Lanner Falcon', 'Falco biarmicus', 'Средиземноморский сокол', id FROM birds_class WHERE name_en = 'Falco'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Stepes piekūns', 'Saker Falcon', 'Falco cherrug', 'Балобан', id FROM birds_class WHERE name_en = 'Falco'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Medību piekūns', 'Gyrfalcon', 'Falco rusticolus', 'Кречет', id FROM birds_class WHERE name_en = 'Falco'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais ormanītis', 'Little Crake', 'Porzana parva', 'Малый погоныш', id FROM birds_class WHERE name_en = 'Zapornia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ceru ormanītis', 'Baillon''s Crake', 'Porzana pusilla', 'Погоныш-крошка', id FROM birds_class WHERE name_en = 'Zapornia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ormanītis', 'Spotted Crake', 'Porzana porzana', 'Погоныш', id FROM birds_class WHERE name_en = 'Porzana'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lielā sīga', 'Great Bustard', 'Otis tarda', 'Дрофа', id FROM birds_class WHERE name_en = 'Otis'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Apkakles sīga', 'Macqueen''s Bustard', 'Chlamydotis macqueenii', 'Вихляй', id FROM birds_class WHERE name_en = 'Chlamydotis'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazā sīga', 'Little Bustard', 'Tetrax tetrax', 'Стрепет', id FROM birds_class WHERE name_en = 'Tetrax'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tundras tārtiņš', 'Pacific Golden Plover', 'Pluvialis fulva', 'Бурокрылая ржанка', id FROM birds_class WHERE name_en = 'Pluvialis'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tuksneša tārtiņš', 'Greater Sand Plover', 'Charadrius leschenaultii crassirostris/ leschenaultii', 'Большеклювый зуёк', id FROM birds_class WHERE name_en = 'Charadrius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Morinella tārtiņš', 'Eurasian Dotterel', 'Charadrius morinellus', 'Хрустан', id FROM birds_class WHERE name_en = 'Charadrius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Garstilbis', 'Black-winged Stilt', 'Himantopus himantopus', 'Ходулочник', id FROM birds_class WHERE name_en = 'Himantopus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Avozeta', 'Pied Avocet', 'Recurvirostra avosetta', 'Шилоклювка', id FROM birds_class WHERE name_en = 'Recurvirostra'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Terekija', 'Terek Sandpiper', 'Xenus cinereus', 'Мородунка', id FROM birds_class WHERE name_en = 'Xenus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tumšā tilbīte', 'Spotted Redshank', 'Tringa erythropus', 'Щёголь', id FROM birds_class WHERE name_en = 'Tringa'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dīķu tilbīte', 'Marsh Sandpiper', 'Tringa stagnatilis', 'Поручейник', id FROM birds_class WHERE name_en = 'Tringa'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Pļavu tilbīte', 'Common Redshank', 'Tringa totanus', 'Травник', id FROM birds_class WHERE name_en = 'Tringa'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Temminka šņibītis', 'Temminck''s Stint', 'Calidris temminckii', 'Белохвостый песочник', id FROM birds_class WHERE name_en = 'Calidris'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tundras šņibītis', 'Pectoral Sandpiper', 'Calidris melanotos', 'Дутыш', id FROM birds_class WHERE name_en = 'Calidris'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Jūras šņibītis', 'Purple Sandpiper', 'Calidris maritima', 'Морской песочник', id FROM birds_class WHERE name_en = 'Calidris'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Līkšņibītis', 'Curlew Sandpiper', 'Calidris ferruginea', 'Краснозобик', id FROM birds_class WHERE name_en = 'Calidris'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Vistilbe', 'Jack Snipe', 'Lymnocryptes minimus', 'Гаршнеп', id FROM birds_class WHERE name_en = 'Lymnocryptes'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ķikuts', 'Great Snipe', 'Gallinago media', 'Дупель', id FROM birds_class WHERE name_en = 'Gallinago'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Platknābja pūslītis', 'Red Phalarope', 'Phalaropus fulicarius', 'Плосконосый плавунчик', id FROM birds_class WHERE name_en = 'Phalaropus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnspārnu bezdelīgtārtiņš', 'Black-winged Pratincole', 'Glareola nordmanni', 'Степная тиркушка', id FROM birds_class WHERE name_en = 'Glareola'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Šķeltastes kaija', 'Sabine''s Gull', 'Xema sabini', 'Вилохвостая чайка', id FROM birds_class WHERE name_en = 'Xema'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais ķīris', 'Little Gull', 'Hydrocoloeus minutus', 'Малая чайка', id FROM birds_class WHERE name_en = 'Hydrocoloeus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sārtā kaija', 'Ross''s Gull', 'Rhodostethia rosea', 'Розовая чайка', id FROM birds_class WHERE name_en = 'Rhodostethia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melngalvas kaija', 'Mediterranean Gull', 'Ichthyaetus melanocephalus', 'Черноголовая чайка', id FROM birds_class WHERE name_en = 'Ichthyaetus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Zivju kaija', 'Pallas''s Gull', 'Ichthyaetus ichthyaetus', 'Черноголовый хохотун', id FROM birds_class WHERE name_en = 'Ichthyaetus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Vidusjūras kaija', 'Yellow-legged Gull', 'Larus michahellis', 'Средиземноморская чайка', id FROM birds_class WHERE name_en = 'Larus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Kaspijas kaija', 'Caspian Gull', 'Larus cachinnans', 'Хохотунья', id FROM birds_class WHERE name_en = 'Larus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazā polārkaija', 'Iceland Gull', 'Larus glaucoides', 'Полярная чайка', id FROM birds_class WHERE name_en = 'Larus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Kamčatkas kaija', 'Slaty-backed Gull', 'Larus schistisagus', 'Тихоокеанская чайка', id FROM birds_class WHERE name_en = 'Larus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltspārnu zīriņš', 'White-winged Tern', 'Chlidonias leucopterus', 'Белокрылая болотная крачка', id FROM birds_class WHERE name_en = 'Chlidonias'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Jūras zīriņš', 'Arctic Tern', 'Sterna paradisaea', 'Полярная крачка', id FROM birds_class WHERE name_en = 'Sterna'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lielā klijkaija', 'Great Skua', 'Stercorarius skua', 'Большой поморник', id FROM birds_class WHERE name_en = 'Stercorarius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Vidējā klijkaija', 'Pomarine Skua', 'Stercorarius pomarinus', 'Средний поморник', id FROM birds_class WHERE name_en = 'Stercorarius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Īsastes klijkaija', 'Parasitic Jaeger', 'Stercorarius parasiticus', 'Короткохвостый поморник', id FROM birds_class WHERE name_en = 'Stercorarius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Garastes klijkaija', 'Long-tailed Jaeger', 'Stercorarius longicaudus', 'Длиннохвостый поморник', id FROM birds_class WHERE name_en = 'Stercorarius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais alks', 'Little Auk', 'Alle alle', 'Люрик', id FROM birds_class WHERE name_en = 'Alle'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Resnknābja kaira', 'Thick-billed Murre', 'Uria lomvia', 'Толстоклювая кайра', id FROM birds_class WHERE name_en = 'Uria'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Stepes smilšvistiņa', 'Pallas''s Sandgrouse', 'Syrrhaptes paradoxus', 'Саджа', id FROM birds_class WHERE name_en = 'Syrrhaptes'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Krāmera papagailis', 'Rose-ringed Parakeet', 'Psittacula krameri', 'Индийский кольчатый попугай', id FROM birds_class WHERE name_en = 'Psittacula'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltā pūce', 'Snowy Owl', 'Bubo scandiacus', 'Белая сова', id FROM birds_class WHERE name_en = 'Bubo'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Bišu dzenis', 'European Bee-eater', 'Merops apiaster', 'Золотистая щурка', id FROM birds_class WHERE name_en = 'Merops'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Rudastes čakste', 'Red-tailed Shrike', 'Lanius phoenicuroides', 'Рыжехвостый жулан', id FROM birds_class WHERE name_en = 'Lanius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Daurijas čakste', 'Isabelline Shrike', 'Lanius isabellinus', 'Буланый жулан', id FROM birds_class WHERE name_en = 'Lanius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnpieres čakste', 'Lesser Grey Shrike', 'Lanius minor', 'Чернолобый сорокопут', id FROM birds_class WHERE name_en = 'Lanius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Bēdrozis', 'Siberian Jay', 'Perisoreus infaustus', 'Кукша', id FROM birds_class WHERE name_en = 'Perisoreus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Riekstrozis', 'Spotted Nutcracker', 'Nucifraga caryocatactes', 'Кедровка', id FROM birds_class WHERE name_en = 'Nucifraga'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Īspirkstu cīrulis', 'Greater Short-toed Lark', 'Calandrella brachydactyla', 'Малый жаворонок', id FROM birds_class WHERE name_en = 'Calandrella'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Gaišzilā zīlīte', 'Azure Tit', 'Cyanistes cyanus', 'Белая лазоревка', id FROM birds_class WHERE name_en = 'Cyanistes'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Īspirkstu mizložņa', 'Short-toed Treecreeper', 'Certhia brachydactyla', 'Короткопалая пищуха', id FROM birds_class WHERE name_en = 'Certhia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tumšais ķauķītis', 'Dusky Warbler', 'Phylloscopus fuscatus', 'Бурая пеночка', id FROM birds_class WHERE name_en = 'Phylloscopus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Švarca ķauķītis', 'Radde''s Warbler', 'Phylloscopus schwarzi', 'Толстоклювая пеночка', id FROM birds_class WHERE name_en = 'Phylloscopus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sibīrijas ķauķītis', 'Pallas''s Leaf Warbler', 'Phylloscopus proregulus', 'Корольковая пеночка', id FROM birds_class WHERE name_en = 'Phylloscopus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dzeltensvītru ķauķītis', 'Yellow-browed Warbler', 'Phylloscopus inornatus', 'Пеночка-зарничка', id FROM birds_class WHERE name_en = 'Phylloscopus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Hjūma ķauķītis', 'Hume''s Warbler', 'Phylloscopus humei', 'Тусклая зарничка', id FROM birds_class WHERE name_en = 'Phylloscopus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Klusais ķauķis', 'Booted Warbler', 'Hippolais caligata', 'Северная бормотушка', id FROM birds_class WHERE name_en = 'Iduna'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Grīšļu ķauķis', 'Aquatic Warbler', 'Acrocephalus paludicola', 'Вертлявая камышовка', id FROM birds_class WHERE name_en = 'Acrocephalus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Palieņu ķauķis', 'Paddyfield Warbler', 'Acrocephalus agricola', 'Индийская камышовка', id FROM birds_class WHERE name_en = 'Acrocephalus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lāsainais ķauķis', 'Lanceolated Warbler', 'Locustella lanceolata', 'Пятнистый сверчок', id FROM birds_class WHERE name_en = 'Locustella'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Pallasa ķauķis', 'Pallas''s Grasshopper Warbler', 'Locustella certhiola', 'Певчий сверчок', id FROM birds_class WHERE name_en = 'Helopsaltes'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dārza ķauķis', 'Garden Warbler', 'Sylvia borin', 'Садовая славка', id FROM birds_class WHERE name_en = 'Sylvia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tuksneša ķauķis', 'Asian Desert Warbler', 'Sylvia nana', 'Пустынная славка', id FROM birds_class WHERE name_en = 'Curruca'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltkakla mušķērājs', 'Collared Flycatcher', 'Ficedula albicollis', 'Мухоловка-белошейка', id FROM birds_class WHERE name_en = 'Ficedula'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais mušķērājs', 'Red-breasted Flycatcher', 'Ficedula parva', 'Малая мухоловка', id FROM birds_class WHERE name_en = 'Ficedula'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lakstīgala', 'Thrush Nightingale', 'Luscinia luscinia', 'Обыкновенный соловей', id FROM birds_class WHERE name_en = 'Luscinia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Rietumu lakstīgala', 'Common Nightingale', 'Luscinia megarhynchos', 'Западный соловей', id FROM birds_class WHERE name_en = 'Luscinia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sibīrijas rubīnrīklīte', 'Siberian Rubythroat', 'Luscinia calliope', 'Соловей-красношейка', id FROM birds_class WHERE name_en = 'Calliope'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Zilastīte', 'Red-flanked bluetail', 'Tarsiger cyanurus', 'Синехвостка', id FROM birds_class WHERE name_en = 'Tarsiger'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Daglā čakstīte', 'Pied Wheatear', 'Oenanthe pleschanka', 'Каменка-плешанка', id FROM birds_class WHERE name_en = 'Oenanthe'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tuksneša čakstīte', 'Desert Wheatear', 'Oenanthe deserti', 'Пустынная каменка', id FROM birds_class WHERE name_en = 'Oenanthe'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Smiltāju čakstīte', 'Isabelline Wheatear', 'Oenanthe isabellina', 'Каменка-плясунья', id FROM birds_class WHERE name_en = 'Oenanthe'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sibīrijas čakstīte', 'Siberian Stonechat', 'Saxicola maurus', 'Сибирский черноголовый чекан', id FROM birds_class WHERE name_en = 'Saxicola'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Raibais zemesstrazds', 'Scaly Thrush', 'Zoothera dauma', 'Пёстрый дрозд', id FROM birds_class WHERE name_en = 'Zoothera'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnrīkles strazds', 'Black-throated Thrush', 'Turdus atrogularis', 'Чернозобый дрозд', id FROM birds_class WHERE name_en = 'Turdus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sārtais strazds', 'Rosy Starling', 'Pastor roseus', 'Розовый скворец', id FROM birds_class WHERE name_en = 'Pastor'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Citroncielava', 'Citrine Wagtail', 'Motacilla citreola', 'Желтоголовая трясогузка', id FROM birds_class WHERE name_en = 'Motacilla'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lielā čipste', 'Richard''s Pipit', 'Anthus richardi', 'Степной конёк', id FROM birds_class WHERE name_en = 'Anthus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sarkanrīkles čipste', 'Red-throated Pipit', 'Anthus cervinus', 'Краснозобый конёк', id FROM birds_class WHERE name_en = 'Anthus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Priežu stērste', 'Pine Bunting', 'Emberiza leucocephalos', 'Белошапочная овсянка', id FROM birds_class WHERE name_en = 'Emberiza'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dārza stērste', 'Ortolan Bunting', 'Emberiza hortulana', 'Садовая овсянка', id FROM birds_class WHERE name_en = 'Emberiza'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazā stērste', 'Little Bunting', 'Emberiza pusilla', 'Овсянка-крошка', id FROM birds_class WHERE name_en = 'Emberiza'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Birztalu stērste', 'Yellow-breasted Bunting', 'Emberiza aureola', 'Дубровник', id FROM birds_class WHERE name_en = 'Emberiza'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melngalvas stērste', 'Black-headed Bunting', 'Emberiza melanocephala', 'Черноголовая овсянка', id FROM birds_class WHERE name_en = 'Emberiza'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Priežu krustknābis', 'Parrot Crossbill', 'Loxia pytyopsittacus', 'Клёст-сосновик', id FROM birds_class WHERE name_en = 'Loxia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais ķeģis', 'Lesser Redpoll', 'Acanthis cabaret', 'Воробьинообразные', id FROM birds_class WHERE name_en = 'Acanthis'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Acteku kaija', 'Laughing Gull', 'Leucophaeus atricilla', 'Ацтекская чайка', id FROM birds_class WHERE name_en = 'Leucophaeus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Taigas sējas zoss', 'Taiga Bean Goose', 'Anser fabalis', 'Гуменник', id FROM birds_class WHERE name_en = 'Anser'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lopu gārnis', 'Cattle Egret', 'Bubulcus ibis', 'Египетская цапля', id FROM birds_class WHERE name_en = 'Bubulcus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Nakts gārnis', 'Black-crowned Night Heron', 'Nycticorax nycticorax', 'Обыкновенная кваква', id FROM birds_class WHERE name_en = 'Nycticorax'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Karošknābis', 'Eurasian Spoonbill', 'Platalea leucorodia', 'Обыкновенная колпица', id FROM birds_class WHERE name_en = 'Platalea'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Zivju ērglis', 'Osprey', 'Pandion haliaetus', 'Скопа', id FROM birds_class WHERE name_en = 'Pandion'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sarkanā klija', 'Red Kite', 'Milvus milvus', 'Красный коршун', id FROM birds_class WHERE name_en = 'Milvus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnā klija', 'Black Kite', 'Milvus migrans', 'Чёрный коршун', id FROM birds_class WHERE name_en = 'Milvus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Zvirbuļu vanags', 'Eurasian Sparrowhawk', 'Accipiter nisus', 'Ястреб-перепелятник', id FROM birds_class WHERE name_en = 'Accipiter'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Klinšu ērglis', 'Golden Eagle', 'Aquila chrysaetos', 'Беркут', id FROM birds_class WHERE name_en = 'Aquila'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Purva piekūns', 'Merlin', 'Falco columbarius', 'Дербник', id FROM birds_class WHERE name_en = 'Falco'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lielais piekūns', 'Peregrine Falcon', 'Falco peregrinus', 'Сапсан', id FROM birds_class WHERE name_en = 'Falco'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dumbrcālis', 'Water Rail', 'Rallus aquaticus', 'Водяной пастушок', id FROM birds_class WHERE name_en = 'Rallus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dzeltenais tārtiņš', 'European Golden Plover', 'Pluvialis apricaria', 'Золотистая ржанка', id FROM birds_class WHERE name_en = 'Pluvialis'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Jūras tārtiņš', 'Kentish Plover', 'Charadrius alexandrinus', 'Морской зуёк', id FROM birds_class WHERE name_en = 'Charadrius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lietuvainis', 'Whimbrel', 'Numenius phaeopus', 'Средний кроншнеп', id FROM birds_class WHERE name_en = 'Numenius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnā puskuitala', 'Black-tailed Godwit', 'Limosa limosa', 'Большой веретенник', id FROM birds_class WHERE name_en = 'Limosa'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sarkanā puskuitala', 'Bar-tailed Godwit', 'Limosa lapponica', 'Малый веретенник', id FROM birds_class WHERE name_en = 'Limosa'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Akmeņtārtiņš', 'Ruddy Turnstone', 'Arenaria interpres', 'Камнешарка', id FROM birds_class WHERE name_en = 'Arenaria'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lielais šņibītis', 'Red Knot', 'Calidris canutus', 'Исландский песочник', id FROM birds_class WHERE name_en = 'Calidris'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dūņšņibītis', 'Broad-billed Sandpiper', 'Limicola falcinellus', 'Грязовик', id FROM birds_class WHERE name_en = 'Calidris'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Brūnspārnu bezdelīgtārtiņš', 'Collared Pratincole', 'Glareola pratincola', 'Луговая тиркушка', id FROM birds_class WHERE name_en = 'Glareola'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Trīspirkstu kaija', 'Black-legged Kittiwake', 'Rissa tridactyla', 'Обыкновенная моевка', id FROM birds_class WHERE name_en = 'Rissa'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lielā polārkaija', 'Glaucous Gull', 'Larus hyperboreus', 'Бургомистр', id FROM birds_class WHERE name_en = 'Larus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazais zīriņš', 'Little Tern', 'Sternula albifrons', 'Малая крачка', id FROM birds_class WHERE name_en = 'Sternula'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltvaigu zīriņš', 'Whiskered Tern', 'Chlidonias hybrida', 'Белощёкая болотная крачка', id FROM birds_class WHERE name_en = 'Chlidonias'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tievknābja kaira', 'Common Murre', 'Uria aalge', 'Тонкоклювая кайра', id FROM birds_class WHERE name_en = 'Uria'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lielais alks', 'Razorbill', 'Alca torda', 'Гагарка', id FROM birds_class WHERE name_en = 'Alca'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnais alks', 'Black Guillemot', 'Cepphus grylle', 'Обыкновенный чистик', id FROM birds_class WHERE name_en = 'Cepphus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Parastā ūbele', 'European Turtle Dove', 'Streptopelia turtur', 'Обыкновенная горлица', id FROM birds_class WHERE name_en = 'Streptopelia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Austrumu ūbele', 'Oriental Turtle Dove', 'Streptopelia orientalis', 'Большая горлица', id FROM birds_class WHERE name_en = 'Streptopelia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Gredzenūbele', 'Eurasian Collared Dove', 'Streptopelia decaocto', 'Кольчатая горлица', id FROM birds_class WHERE name_en = 'Streptopelia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dzeguze', 'Common Cuckoo', 'Cuculus canorus', 'Обыкновенная кукушка', id FROM birds_class WHERE name_en = 'Cuculus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Plīvurpūce', 'Barn Owl', 'Tyto alba', 'Обыкновенная сипуха', id FROM birds_class WHERE name_en = 'Tyto'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mazā ausainā pūcīte', 'Eurasian Scops Owl', 'Otus scops', 'Сплюшка', id FROM birds_class WHERE name_en = 'Otus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ūpis', 'Eurasian Eagle-Owl', 'Bubo bubo', 'Филин', id FROM birds_class WHERE name_en = 'Bubo'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Svītrainā pūce', 'Northern Hawk-Owl', 'Surnia ulula', 'Ястребиная сова', id FROM birds_class WHERE name_en = 'Surnia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Apodziņš', 'Eurasian Pygmy Owl', 'Glaucidium passerinum', 'Воробьиный сыч', id FROM birds_class WHERE name_en = 'Glaucidium'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Mājas apogs', 'Little Owl', 'Athene noctua', 'Домовый сыч', id FROM birds_class WHERE name_en = 'Athene'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Urālpūce', 'Ural Owl', 'Strix uralensis', 'Длиннохвостая неясыть', id FROM birds_class WHERE name_en = 'Strix'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ziemeļu pūce', 'Great Gray Owl', 'Strix nebulosa', 'Бородатая неясыть', id FROM birds_class WHERE name_en = 'Strix'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ausainā pūce', 'Long-eared Owl', 'Asio otus', 'Ушастая сова', id FROM birds_class WHERE name_en = 'Asio'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Purva pūce', 'Short-eared Owl', 'Asio flammeus', 'Болотная сова', id FROM birds_class WHERE name_en = 'Asio'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Bikšainais apogs', 'Boreal Owl', 'Aegolius funereus', 'Мохноногий сыч', id FROM birds_class WHERE name_en = 'Aegolius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Vakarlēpis', 'European Nightjar', 'Caprimulgus europaeus', 'Обыкновенный козодой', id FROM birds_class WHERE name_en = 'Caprimulgus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Trīspirkstu dzenis', 'Eurasian Three-toed Woodpecker', 'Picoides tridactylus', 'Трёхпалый дятел', id FROM birds_class WHERE name_en = 'Picoides'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Zaļā dzilna', 'European Green Woodpecker', 'Picus viridis', 'Зелёный дятел', id FROM birds_class WHERE name_en = 'Picus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Vālodze', 'Eurasian Golden Oriole', 'Oriolus oriolus', 'Обыкновенная иволга', id FROM birds_class WHERE name_en = 'Oriolus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Melnā vārna', 'Carrion Crow', 'Corvus corone', 'Чёрная ворона', id FROM birds_class WHERE name_en = 'Corvus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Cekulainais cīrulis', 'Crested Lark', 'Galerida cristata', 'Хохлатый жаворонок', id FROM birds_class WHERE name_en = 'Galerida'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ausainais cīrulis', 'Horned Lark', 'Eremophila alpestris', 'Рогатый жаворонок', id FROM birds_class WHERE name_en = 'Eremophila'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Krastu čurkste', 'Sand Martin', 'Riparia riparia', 'Береговушка', id FROM birds_class WHERE name_en = 'Riparia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Daurijas bezdelīga', 'Red-rumped Swallow', 'Cecropis daurica', 'Рыжепоясничная ласточка', id FROM birds_class WHERE name_en = 'Cecropis'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ūdensstrazds', 'White-throated Dipper', 'Cinclus cinclus', 'Оляпка', id FROM birds_class WHERE name_en = 'Cinclus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ziemeļu ķauķītis', 'Arctic Warbler', 'Phylloscopus borealis', 'Пеночка-таловка', id FROM birds_class WHERE name_en = 'Phylloscopus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Zaļais ķauķītis', 'Greenish Warbler', 'Phylloscopus trochiloides', 'Зелёная пеночка', id FROM birds_class WHERE name_en = 'Phylloscopus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ezeru ķauķis', 'Eurasian Reed Warbler', 'Acrocephalus scirpaceus', 'Тростниковая камышовка', id FROM birds_class WHERE name_en = 'Acrocephalus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Kārklu ķauķis', 'Common Grasshopper Warbler', 'Locustella naevia', 'Обыкновенный сверчок', id FROM birds_class WHERE name_en = 'Locustella'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Seivi ķauķis', 'Savi''s Warbler', 'Locustella luscinioides', 'Соловьиный сверчок', id FROM birds_class WHERE name_en = 'Locustella'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Svītrainais ķauķis', 'Barred Warbler', 'Sylvia nisoria', 'Ястребиная славка', id FROM birds_class WHERE name_en = 'Curruca'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Zilrīklīte', 'Bluethroat', 'Luscinia svecica', 'Варакушка', id FROM birds_class WHERE name_en = 'Luscinia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Tumšā čakstīte', 'European Stonechat', 'Saxicola torquatus', 'Африканский черноголовый чекан', id FROM birds_class WHERE name_en = 'Saxicola'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Apkakles strazds', 'Ring Ouzel', 'Turdus torquatus', 'Белозобый дрозд', id FROM birds_class WHERE name_en = 'Turdus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sibīrijas peļkājīte', 'Siberian Accentor', 'Prunella montanella', 'Сибирская завирушка', id FROM birds_class WHERE name_en = 'Prunella'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Peļkājīte', 'Hedge Accentor (Dunnock)', 'Prunella modularis', 'Лесная завирушка', id FROM birds_class WHERE name_en = 'Prunella'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Pelēkā cielava', 'Grey Wagtail', 'Motacilla cinerea', 'Горная трясогузка', id FROM birds_class WHERE name_en = 'Motacilla'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Stepes čipste', 'Tawny Pipit', 'Anthus campestris', 'Полевой конёк', id FROM birds_class WHERE name_en = 'Anthus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ūdeņu čipste', 'Water Pipit', 'Anthus spinoletta', 'Горный конёк', id FROM birds_class WHERE name_en = 'Anthus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Akmeņu čipste', 'Eurasian Rock Pipit', 'Anthus petrosus', 'Береговой конёк', id FROM birds_class WHERE name_en = 'Anthus'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Zīdaste', 'Bohemian Waxwing', 'Bombycilla garrulus', 'Свиристель', id FROM birds_class WHERE name_en = 'Bombycilla'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lapzemes stērste', 'Lapland Longspur', 'Calcarius lapponicus', 'Лапландский подорожник', id FROM birds_class WHERE name_en = 'Calcarius'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Sniedze', 'Snow Bunting', 'Plectrophenax nivalis', 'Пуночка', id FROM birds_class WHERE name_en = 'Plectrophenax'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Meža stērste', 'Rustic Bunting', 'Emberiza rustica', 'Овсянка-ремез', id FROM birds_class WHERE name_en = 'Emberiza'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Lielā stērste', 'Corn Bunting', 'Emberiza calandra', 'Просянка', id FROM birds_class WHERE name_en = 'Emberiza'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Ziemeļu svilpis', 'Pine Grosbeak', 'Pinicola enucleator', 'Обыкновенный щур', id FROM birds_class WHERE name_en = 'Pinicola'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Baltsvītru krustknābis', 'Two-barred Crossbill', 'Loxia leucoptera', 'Белокрылый клёст', id FROM birds_class WHERE name_en = 'Loxia'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Parastais ķeģis', 'Common Redpoll', 'Acanthis flammea', 'Чечётка', id FROM birds_class WHERE name_en = 'Acanthis'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Gaišais ķeģis', 'Arctic Redpoll', 'Acanthis hornemanni', 'Тундряная чечётка', id FROM birds_class WHERE name_en = 'Acanthis'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Kalnu ķeģis', 'Twite', 'Carduelis flavirostris', 'Горная коноплянка', id FROM birds_class WHERE name_en = 'Linaria'`)
  pgm.sql(`INSERT INTO birds_names (name_lv, name_en, name_lat, name_ru, genus)
    SELECT 'Dižknābis', 'Hawfinch', 'Coccothraustes coccothraustes', 'Обыкновенный дубонос', id FROM birds_class WHERE name_en = 'Coccothraustes'`)
}

exports.down = pgm => {}
