/* eslint-disable camelcase */

exports.shorthands = undefined

exports.up = pgm => {
  // Orders
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru) VALUES
    ('Dzegužveidīgie', 'Cuculiformes', 'Кукушкообразные'),
    ('Flamingveidīgie', 'Phoenicopteriformes', 'Фламингообразные'),
    ('Gārgaļveidīgie', 'Gaviiformes', 'Гагарообразные'),
    ('Lēļveidīgie', 'Caprimulgiformes', 'Козодоеобразные'),
    ('Papagaiļveidīgie', 'Psittaciformes', 'Попугаеобразные'),
    ('Smilšvistiņveidīgie', 'Pterocliformes', 'Рябкообразные'),
    ('Sīgveidīgie', 'Otidiformes', 'Дрофообразные'),
    ('Vētrasputni', 'Procellariiformes', 'Буревестникообразные')
  `)

  // Families
  //SELECT 'Baložu dzimta', 'Columbidae', 'Голубиные', id FROM birds_class WHERE name_en = 'Columbiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Alku dzimta', 'Alcidae', 'Чистиковые', id FROM birds_class WHERE name_en = 'Charadriiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Arktikas stērstu dzimta', 'Calcariidae', 'Подорожниковые', id FROM birds_class WHERE name_en = 'Passeriformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Bezdelīgtārtiņu dzimta', 'Glareolidae', 'Тиркушковые', id FROM birds_class WHERE name_en = 'Charadriiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Bišu dzeņu dzimta', 'Meropidae', 'Щурковые', id FROM birds_class WHERE name_en = 'Coraciiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Burātāju dzimta', 'Hydrobatidae', 'Качурки', id FROM birds_class WHERE name_en = 'Procellariiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Dzegužu dzimta', 'Cuculidae', 'Кукушковые', id FROM birds_class WHERE name_en = 'Cuculiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Flamingu dzimta', 'Phoenicopteridae', 'Фламинговые', id FROM birds_class WHERE name_en = 'Phoenicopteriformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Gārgaļu dzimta', 'Gaviidae', 'Гагаровые', id FROM birds_class WHERE name_en = 'Gaviiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ibisu dzimta', 'Threskiornithidae', 'Ибисовые', id FROM birds_class WHERE name_en = 'Pelecaniformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Klijkaiju dzimta', 'Stercorariidae', 'Поморниковые', id FROM birds_class WHERE name_en = 'Charadriiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Lēļu dzimta', 'Caprimulgidae', 'Настоящие козодои', id FROM birds_class WHERE name_en = 'Caprimulgiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Papagaiļu dzimta', 'Psittaculidae', 'Psittaculidae', id FROM birds_class WHERE name_en = 'Psittaciformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Pelikānu dzimta', 'Pelecanidae', 'Пеликановые', id FROM birds_class WHERE name_en = 'Pelecaniformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Peļkājīšu dzimta', 'Prunellidae', 'Завирушковые', id FROM birds_class WHERE name_en = 'Passeriformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Plīvurpūču dzimta', 'Tytonidae', 'Сипуховые', id FROM birds_class WHERE name_en = 'Strigiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Smilšvistiņu dzimtā', 'Pteroclidae', 'Рябковые', id FROM birds_class WHERE name_en = 'Pterocliformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Sullu dzimta', 'Sulidae', 'Олушевые', id FROM birds_class WHERE name_en = 'Suliformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Sīgu dzimta', 'Otididae', 'Дрофиные', id FROM birds_class WHERE name_en = 'Otidiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Vālodžu dzimta', 'Oriolidae', 'Иволговые', id FROM birds_class WHERE name_en = 'Passeriformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Vētrasputnu dzimta', 'Procellariidae', 'Буревестниковые', id FROM birds_class WHERE name_en = 'Procellariiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Zivjērgļu dzimta', 'Pandionidae', 'Скопиные', id FROM birds_class WHERE name_en = 'Accipitriformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Zīdastu dzimta', 'Bombycillidae', 'Свиристелевые', id FROM birds_class WHERE name_en = 'Passeriformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Īlenknābju dzimta', 'Recurvirostridae', 'Шилоклювковые', id FROM birds_class WHERE name_en = 'Charadriiformes'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ūdensstrazdu dzimta', 'Cinclidae', 'Оляпковые', id FROM birds_class WHERE name_en = 'Passeriformes'`)

  // Geni
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Akmeņtārtiņi', 'Arenaria', 'Камнешарки', id FROM birds_class WHERE name_en = 'Scolopacidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Alki', 'Alca', 'Гагарки', id FROM birds_class WHERE name_en = 'Alcidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Amerikas kaijas', 'Leucophaeus', 'Дельфиновые чайки', id FROM birds_class WHERE name_en = 'Laridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Apkakles sīgas', 'Chlamydotis', 'Дрофы-красотки', id FROM birds_class WHERE name_en = 'Otididae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Apodziņi', 'Glaucidium', 'Воробьиные сычи', id FROM birds_class WHERE name_en = 'Strigidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Apogi', 'Athene', 'Сычи', id FROM birds_class WHERE name_en = 'Strigidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Arktikas stērstes', 'Calcarius', 'Подорожники', id FROM birds_class WHERE name_en = 'Calcariidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Arlekīnpīles', 'Histrionicus', 'Каменушки', id FROM birds_class WHERE name_en = 'Anatidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ausainie cīruļi', 'Eremophila', 'Рогатые жаворонки', id FROM birds_class WHERE name_en = 'Alaudidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ausainās pūces', 'Asio', 'Ушастые совы', id FROM birds_class WHERE name_en = 'Strigidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Austrumu sisinātājķauķi', 'Helopsaltes', 'Helopsaltes', id FROM birds_class WHERE name_en = 'Locustellidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Baltirbes', 'Lagopus', 'Белые куропатки', id FROM birds_class WHERE name_en = 'Phasianidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Bezdelīgtārtiņi', 'Glareola', 'Тиркушки', id FROM birds_class WHERE name_en = 'Glareolidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Bikšainie apogi', 'Aegolius', 'Мохноногие сычи', id FROM birds_class WHERE name_en = 'Strigidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Bišu dzeņi', 'Merops', 'Щурки', id FROM birds_class WHERE name_en = 'Meropidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Blāvie ķauķi', 'Iduna', 'Iduna', id FROM birds_class WHERE name_en = 'Acrocephalidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Brūnie ibisi', 'Plegadis', 'Каравайки', id FROM birds_class WHERE name_en = 'Threskiornithidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Bēdroži', 'Perisoreus', 'Кукши', id FROM birds_class WHERE name_en = 'Corvidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Cekulainie cīruļi', 'Galerida', 'Хохлатые жаворонки', id FROM birds_class WHERE name_en = 'Alaudidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Dižknābji', 'Coccothraustes', 'Дубоносы', id FROM birds_class WHERE name_en = 'Fringillidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Dumbrcāļi', 'Rallus', 'Пастушки', id FROM birds_class WHERE name_en = 'Rallidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Dzeguzes', 'Cuculus', 'Кукушки', id FROM birds_class WHERE name_en = 'Cuculidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Fazāni', 'Phasianus', 'Фазаны', id FROM birds_class WHERE name_en = 'Phasianidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Flamingi', 'Phoenicopterus', 'Фламинго', id FROM birds_class WHERE name_en = 'Phoenicopteridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Garstilbji', 'Himantopus', 'Ходулочники', id FROM birds_class WHERE name_en = 'Recurvirostridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Gredzenkakla papagaiļi', 'Psittacula', 'Кольчатые попугаи', id FROM birds_class WHERE name_en = 'Psittaculidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Gārgales', 'Gavia', 'Гагары', id FROM birds_class WHERE name_en = 'Gaviidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Jūras kraukļi', 'Microcarbo', 'Microcarbo', id FROM birds_class WHERE name_en = 'Phalacrocoracidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Kairas', 'Uria', 'Кайры', id FROM birds_class WHERE name_en = 'Alcidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Karakaras', 'Caracara', 'Каракары-каранчи', id FROM birds_class WHERE name_en = 'Falconidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Karošknābji', 'Platalea', 'Колпицы', id FROM birds_class WHERE name_en = 'Threskiornithidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Klijas', 'Milvus', 'Настоящие коршуны', id FROM birds_class WHERE name_en = 'Accipitridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Klijkaijas', 'Stercorarius', 'Большие поморники', id FROM birds_class WHERE name_en = 'Stercorariidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Krastu čurkstes', 'Riparia', 'Береговые ласточки', id FROM birds_class WHERE name_en = 'Hirundinidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Krustknābji', 'Loxia', 'Клесты', id FROM birds_class WHERE name_en = 'Fringillidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Lakstīgalas', 'Luscinia', 'Соловьи', id FROM birds_class WHERE name_en = 'Muscicapidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Laukirbes', 'Perdix', 'Куропатки', id FROM birds_class WHERE name_en = 'Phasianidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Lielgalvji', 'Netta', 'Нырки', id FROM birds_class WHERE name_en = 'Anatidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Lielās bezdelīgas', 'Cecropis', 'Cecropis', id FROM birds_class WHERE name_en = 'Hirundinidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Lielās sīgas', 'Otis', 'Дрофы', id FROM birds_class WHERE name_en = 'Otididae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Lopu gārņi', 'Bubulcus', 'Египетские цапли', id FROM birds_class WHERE name_en = 'Ardeidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Lēļi', 'Caprimulgus', 'Козодои', id FROM birds_class WHERE name_en = 'Caprimulgidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mandarīnpīles', 'Aix', 'Лесные утки', id FROM birds_class WHERE name_en = 'Anatidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazie alki', 'Alle', 'Люрики', id FROM birds_class WHERE name_en = 'Alcidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazie dumpji', 'Ixobrychus', 'Малые выпи', id FROM birds_class WHERE name_en = 'Ardeidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazie dūkuri', 'Tachybaptus', 'Малые поганки', id FROM birds_class WHERE name_en = 'Podicipedidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazie gārņi', 'Egretta', 'Белые цапли', id FROM birds_class WHERE name_en = 'Ardeidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazie ormanīši', 'Zapornia', 'Погоныши', id FROM birds_class WHERE name_en = 'Rallidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazie zīriņi', 'Sternula', 'Sternula', id FROM birds_class WHERE name_en = 'Laridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazie ķīri', 'Hydrocoloeus', 'Hydrocoloeus', id FROM birds_class WHERE name_en = 'Laridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazās klijas', 'Elanus', 'Дымчатые коршуны', id FROM birds_class WHERE name_en = 'Accipitridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazās pūcītes', 'Otus', 'Совки', id FROM birds_class WHERE name_en = 'Strigidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mazās sīgas', 'Tetrax', 'Стрепеты', id FROM birds_class WHERE name_en = 'Otididae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Medņi', 'Tetrao', 'Глухари', id FROM birds_class WHERE name_en = 'Phasianidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Melnie alki', 'Cepphus', 'Чистики', id FROM birds_class WHERE name_en = 'Alcidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Melnie grifi', 'Aegypius', 'Чёрные грифы', id FROM birds_class WHERE name_en = 'Accipitridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Mežirbes', 'Tetrastes', 'Рябчики', id FROM birds_class WHERE name_en = 'Phasianidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Nakts gārņi', 'Nycticorax', 'Настоящие кваквы', id FROM birds_class WHERE name_en = 'Ardeidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ormanīši', 'Porzana', 'Погоныши', id FROM birds_class WHERE name_en = 'Rallidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Paipalas', 'Coturnix', 'Перепела', id FROM birds_class WHERE name_en = 'Phasianidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Pelikāni', 'Pelecanus', 'Пеликаны', id FROM birds_class WHERE name_en = 'Pelecanidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Peļkājītes', 'Prunella', 'Завирушки', id FROM birds_class WHERE name_en = 'Prunellidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Plīvurpūces', 'Tyto', 'Сипухи', id FROM birds_class WHERE name_en = 'Tytonidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Puskuitalas', 'Limosa', 'Веретенники', id FROM birds_class WHERE name_en = 'Scolopacidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Pūkpīles', 'Somateria', 'Гаги', id FROM birds_class WHERE name_en = 'Anatidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Raibie zemesstrazdi', 'Zoothera', 'Земляные дрозды', id FROM birds_class WHERE name_en = 'Turdidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Riekstroži', 'Nucifraga', 'Кедровки', id FROM birds_class WHERE name_en = 'Corvidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Rubīnrīklītes', 'Calliope', 'Соловьи', id FROM birds_class WHERE name_en = 'Muscicapidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Smilšvistiņas', 'Syrrhaptes', 'Саджи', id FROM birds_class WHERE name_en = 'Pteroclidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Sniedzes', 'Plectrophenax', 'Пуночки', id FROM birds_class WHERE name_en = 'Calcariidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Stellera pūkpīles', 'Polysticta', 'Малые гаги', id FROM birds_class WHERE name_en = 'Anatidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Sullas', 'Morus', 'Morus', id FROM birds_class WHERE name_en = 'Sulidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Svītrainās pūces', 'Surnia', 'Ястребиные совы', id FROM birds_class WHERE name_en = 'Strigidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Sārtie strazdi', 'Pastor', 'Скворцы', id FROM birds_class WHERE name_en = 'Sturnidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Sārtās kaijas', 'Rhodostethia', 'Розовые чайки', id FROM birds_class WHERE name_en = 'Laridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Terekijas', 'Xenus', 'Мородунки', id FROM birds_class WHERE name_en = 'Scolopacidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Tipiskie grifi', 'Gyps', 'Грифы', id FROM birds_class WHERE name_en = 'Accipitridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Trīspirkstu dzeņi', 'Picoides', 'Трёхпалые дятлы', id FROM birds_class WHERE name_en = 'Picidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Trīspirkstu kaijas', 'Rissa', 'Моевки', id FROM birds_class WHERE name_en = 'Laridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Tumšie vētrasputni', 'Ardenna', 'Ardenna', id FROM birds_class WHERE name_en = 'Procellariidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Vanagērgļi', 'Hieraaetus', 'Длиннохвостые орлы', id FROM birds_class WHERE name_en = 'Accipitridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Vistilbes', 'Lymnocryptes', 'Гаршнепы', id FROM birds_class WHERE name_en = 'Scolopacidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Vālodzes', 'Oriolus', 'Иволги', id FROM birds_class WHERE name_en = 'Oriolidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ziemeļu svilpji', 'Pinicola', 'Щуры', id FROM birds_class WHERE name_en = 'Fringillidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ziemeļu vētrasburātāji', 'Hydrobates', 'Вилохвостые качурки', id FROM birds_class WHERE name_en = 'Hydrobatidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Zilastītes', 'Tarsiger', 'Синехвостки', id FROM birds_class WHERE name_en = 'Muscicapidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Zilknābji', 'Oxyura', 'Савки', id FROM birds_class WHERE name_en = 'Anatidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Zivju kaijas', 'Ichthyaetus', 'Ichthyaetus', id FROM birds_class WHERE name_en = 'Laridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Zivjērgļi', 'Pandion', 'Скопы', id FROM birds_class WHERE name_en = 'Pandionidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Zīdastes', 'Bombycilla', 'Свиристели', id FROM birds_class WHERE name_en = 'Bombycillidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Āfrikas_dižpīles', 'Alopochen', 'Нильские гуси', id FROM birds_class WHERE name_en = 'Anatidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Čūskērgļi', 'Circaetus', 'Настоящие змееяды', id FROM birds_class WHERE name_en = 'Accipitridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ērgļu ģints', 'Aquila', 'Орлы', id FROM birds_class WHERE name_en = 'Accipitridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Īlenknābji', 'Recurvirostra', 'Настоящие шилоклювки', id FROM birds_class WHERE name_en = 'Recurvirostridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Īspirkstu cīruļi', 'Calandrella', 'Малые жаворонки', id FROM birds_class WHERE name_en = 'Alaudidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ķeģi', 'Acanthis', 'Чечётки', id FROM birds_class WHERE name_en = 'Fringillidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Šķeltastes kaijas', 'Xema', 'Вилохвостые чайки', id FROM birds_class WHERE name_en = 'Laridae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ūbeles', 'Streptopelia', 'Горлицы', id FROM birds_class WHERE name_en = 'Columbidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ūdensstrazdi', 'Cinclus', 'Оляпки', id FROM birds_class WHERE name_en = 'Cinclidae'`)
  pgm.sql(`INSERT INTO birds_class (name_lv, name_en, name_ru, parent)
    SELECT 'Ūpji', 'Bubo', 'Филины', id FROM birds_class WHERE name_en = 'Strigidae'`)
}

exports.down = pgm => {}
