const langs = ['lv', 'en', 'ru']

const texts = {
  en : {
    maxTries : "You already used maximum attempts! Try new puzzle tomorrow!",
    headerTitle : "Can you name this bird?",
    title : "Birdle - A bird guessing game",
    placeholder0 : "Start typing here",
    placeholder1 : "Five attempts left",
    placeholder2 : "Four attempts left",
    placeholder3 : "Three attempts left",
    placeholder4 : "Two attempts left",
    placeholder5 : "Last chance",
    helptext1 : "The goal is to guess the bird in six attempts",
    helptext2 : "After each attempt, more detailed image of the bird is revealed",
    helptext3 : "You will also see if you've guessed the order, family and genus",
    helptext4 : "Correct answer will reveal the bird",
    helptext5 : "New task every day!",
    wrong1 : "Not even close!",
    wrong2 : "Nice try!",
    wrong3 : "Close enough!",
    wrong4 : "Almost there!",
    defeat : "Better luck next time!",
    right1 : "That was close!",
    right2 : "Good one!",
    right3 : "Great!",
    right4 : "Excellent!",
    yourStats : "Your statistics",
    totalPlayed : "Games played",
    successRate : "Games won",
    stats1 : "First try",
    stats2 : "Second try",
    stats3 : "Third try",
    stats4 : "Fourth try",
    stats5 : "Fifth try",
    stats6 : "Sixth try",
    tweetHeader : "Bird #",
    tweetCWHeaderFail: "I failed to solve today's crossword puzzle. Maybe you will do better?",
    tweetCWPrefix: "I solved",
    tweetPopupPrefix: "You solved",
    tweetPopupFailPrefix: "Today is not a lucky day.",
    tweetCWHeader1 : " the daily crossword in one attempt",
    tweetCWHeader2 : " the daily crossword in two attempts",
    tweetCWHeader3 : " the daily crossword in three attempts",
    tweetCWHeader4 : " the daily crossword in four attempts",
    tweetCWHeader5 : " the daily crossword in five attempts",
    tweetCWHeader6 : " the daily crossword in six attempts",
    attempt1: "Check (last attempt)",
    attempt2: "Check (two attempts left)",
    attempt3: "Check (three attempts left)",
    attempt4: "Check (four attempts left)",
    attempt5: "Check (five attempts left)",
    attempt6: "Check (six attempts left)",
    share : "Share your result",
    rightAnswer : "Right answer is",
    terms : "The birdle.lv website uses functional cookies to provide the desired functionality of the game. Functional cookies are necessary to maintain an active game session, as well as to store statistics of the games played by the player. The birdle.lv website does not request or store any personal data of players, does not create or use cookies from other resources, and does not transfer player statistics to third parties. The site does not use any tools to identify the player's private data, follow the player's activities and preferences, does not create or process analytical information about the player's behavior on the World Wide Web.",
    termsHeader : "Privacy policy",
    taxonomy: "Taxonomy"
  },
  lv : {
    maxTries : "Tu esi izmantojis visus mēģinājumus šodien! Mēgini vēlreiz rīt ar jaunu uzdevumu!",
    headerTitle : "Vai vari nosaukt šo putnu?",
    title : "Birdle - Putnu minēšanas spēle",
    placeholder0 : "Sāc rakstīt šeit",
    placeholder1 : "Palikuši pieci mēģinājumi",
    placeholder2 : "Palikuši četri mēģinājumi",
    placeholder3 : "Palikuši trīs mēģinājumi",
    placeholder4 : "Palikuši divi mēģinājumi",
    placeholder5 : "Pēdējā iespēja",
    helptext1 : "Spēles mērķis ir uzminēt putnu sešos mēģinājumos",
    helptext2 : "Pēc katra mēģinājuma parādās detalizētāka putna bilde",
    helptext3 : "Tu redzēsi, vai ir pareizi noteikta kārta, dzimta un ģints",
    helptext4 : "Pareizā atbilde atvērs putna bildi",
    helptext5 : "Jauns uzdevums katru dienu!",
    wrong1 : "Pat tuvu nav!",
    wrong2 : "Mēģini vēl!",
    wrong3 : "Ļoti silti!",
    wrong4 : "Nu gandrīz!",
    defeat : "Citreiz paveiksies!",
    right1 : "Par mata tiesu!",
    right2 : "Ļoti labi!",
    right3 : "Lieliski!",
    right4 : "Izcili!",
    yourStats : "Tava statistika",
    totalPlayed : "Kopā nospēlēts",
    successRate : "Pareizās atbildes",
    stats1 : "Ar pirmo mēģinājumu",
    stats2 : "Ar otro mēģinājumu",
    stats3 : "Ar trešo mēģinājumu",
    stats4 : "Ar ceturto mēģinājumu",
    stats5 : "Ar piekto mēģinājumu",
    stats6 : "Ar sesto mēģinājumu",
    tweetHeader : "Putns #",
    tweetCWHeaderFail: "Man neizdevās atrisināt šodienas krustvārdu mīklu. Varbūt Tev veiksies labāk?",
    tweetCWPrefix: "Es atrisināju",
    tweetPopupPrefix: "Tu atrisināji",
    tweetPopupFailPrefix: "Šodien nepaveicas, bet nepārdzīvo.",
    tweetCWHeader1 : " dienas krustvārdu mīklu vienā mēģinājumā",
    tweetCWHeader2 : " dienas krustvārdu mīklu divos mēģinājumos",
    tweetCWHeader3 : " dienas krustvārdu mīklu trīs mēģinājumos",
    tweetCWHeader4 : " dienas krustvārdu mīklu četros mēģinājumos",
    tweetCWHeader5 : " dienas krustvārdu mīklu piecos mēģinājumos",
    tweetCWHeader6 : " dienas krustvārdu mīklu sešos mēģinājumos",
    attempt1: "Pārbaudīt (pēdējais mēģinājums)",
    attempt2: "Pārbaudīt (palika divi mēģinājumi)",
    attempt3: "Pārbaudīt (palika trīs mēģinājumi)",
    attempt4: "Pārbaudīt (palika četri mēģinājumi)",
    attempt5: "Pārbaudīt (palika pieci mēģinājumi)",
    attempt6: "Pārbaudīt (palika seši mēģinājumi)",
    share : "Dalies ar rezultātu",
    rightAnswer : "Pareizā atbilde ir",
    terms : "birdle.lv vietne izmanto funkcionālās sīkdatnes spēles funkcionalitātes nodrošināšanai. Funkcionālās sīkdatnes ir nepieciešamas, lai uzturētu aktīvu spēles sesiju, kā arī spēlētāja nospēlēto spēļu statistikas glabāšanai. birdle.lv vietne nepieprasa un neuzglabā nekādus spēlētāju privātdatus, neveido un neizmanto citu resursu sīkdatnes un nenodod spēlētāju statistiku trešām personām. Vietne neizmanto nekādus rīkus, lai identificētu spēlētāja privātdatus, sekotu spēlētāja aktivitātēm un preferencēm, neveido un neprocesē analitisko informāciju par spēlētāju uzvedību globālajā tīmeklī.",
    termsHeader : "Privātuma politika",
    taxonomy: "Taksonomija"
  },
  ru : {
    maxTries : "Ты уже использовал все попытки сегодня! Попробуй ещё раз завтра!",
    headerTitle : "Можешь ли назвать эту птицу?",
    title : "Birdle - Игра для любителей птиц",
    placeholder0 : "Начинай писать здесь",
    placeholder1 : "Осталось пять попыток",
    placeholder2 : "Остались четыре попытки",
    placeholder3 : "Остались три попытки",
    placeholder4 : "Остались две попытки",
    placeholder5 : "Последний шанс",
    helptext1 : "Цель игры - угадать имя птицы с шести попыток",
    helptext2 : "После каждой попытки открывается более детальное изображение",
    helptext3 : "Ты увидишь, угадал ли ты отряд, семейство и род",
    helptext4 : "При правильном ответе появится фото птицы",
    helptext5 : "Новое задание каждый день!",
    wrong1 : "Вообще не то!",
    wrong2 : "Уже ближе!",
    wrong3 : "Тепло!",
    wrong4 : "Теплее!",
    defeat : "Повезёт в другой раз!",
    right1 : "На волоске!",
    right2 : "Неплохо!",
    right3 : "Отлично!",
    right4 : "Великолепно!",
    yourStats : "Твоя статистика",
    totalPlayed : "Всего сыграно",
    successRate : "Правильных ответов",
    stats1 : "С первой попытки",
    stats2 : "Со второй попытки",
    stats3 : "С третьей попытки",
    stats4 : "С четвёртой попытки",
    stats5 : "С пятой попытки",
    stats6 : "С шестой попытки",
    tweetHeader : "Птица №",
    tweetCWHeaderFail: "Мне не удалось разгадать сегодняшний кроссворд. Может, у тебя получится лучше?",
    tweetCWPrefix: "Мне удалось",
    tweetPopupPrefix: "Тебе удалось",
    tweetPopupFailPrefix: "Не повезло сегодня.",
    tweetCWHeader1: " разгадать сегодняшний кроссворд с первой попытки",
    tweetCWHeader2: " разгадать сегодняшний кроссворд со второй попытки",
    tweetCWHeader3: " разгадать сегодняшний кроссворд с третьей попытки",
    tweetCWHeader4: " разгадать сегодняшний кроссворд с четвёртой попытки",
    tweetCWHeader5: " разгадать сегодняшний кроссворд с пятой попытки",
    tweetCWHeader6: " разгадать сегодняшний кроссворд с шестой попытки",
    attempt1: "Проверить (последняя попытка)",
    attempt2: "Проверить (остались две попытки)",
    attempt3: "Проверить (остались три попытки)",
    attempt4: "Проверить (остались четыре попытки)",
    attempt5: "Проверить (осталось пять попыток)",
    attempt6: "Проверить (осталось шесть попыток)",
    share : "Поделись результатом",
    rightAnswer : "Правильный ответ",
    terms : "Сайт birdle.lv использует функциональные файлы cookie для обеспечения функциональности игры. Функциональные файлы cookie необходимы для поддержания активной игровой сессии, а также для хранения статистики сыгранных игроком игр. Сайт birdle.lv не запрашивает и не хранит никаких персональных данных игроков, не создает и не использует файлы cookie с других ресурсов, а также не передает статистику игроков третьим лицам. Сайт не использует никаких инструментов для идентификации личных данных игрока, слежения за действиями и предпочтениями игрока, не создает и не обрабатывает аналитическую информацию о поведении игрока во Всемирной паутине.",
    termsHeader : "Политика приватности",
    taxonomy: "Таксономия"
  }
}

const text = (lang, code) => texts[lang][code] ?? ('_' + code)

const errorMessage = (lang, code) => (
  {
    event : "showError",
    target : '.game',
    errorMessage : text(lang, code)
  }
)

module.exports = { langs, texts, text, errorMessage }
